# -*- coding: utf-8 -*-
"""Python-AI-Travel-Planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K43At0WutS7nvRhELn1iJQ272PSGonL9
"""

import requests
from rich import print
from rich.markdown import Markdown


# generate weather function in origin and destination
def generate_weather(location):
 api_key = "b4697434f3a4b96oc63c0bff5tca4166"
 api_url = f"https://api.shecodes.io/weather/v1/current?query={location}&key={api_key}&units=metric"

# *** call weather api ***
 response = requests.get(api_url)
 response_data = response.json()
 temperature = round(response_data["temperature"] ["current"])
 condition = response_data["condition"]["description"]

 print(f"\nThe temperature in [bold]{location} [/bold] is [bold]{temperature}[/bold] degrees C and it is [bold]{condition}[/bold]\n" )


# generate itinerary function
def generate_itinerary(origin, destination, duration):
  print(f"\n Generating itinerary from {origin} to {destination}...⏳\n")

# call the shecodes AI API to get the itinerary
  prompt = f"Generate a travel itinerary from {origin} to {destination} in {duration} days. This is a road trip, keep it to max 15 lines, add bulletpoints, add estimated cost for each day and emojis to make it more readable"
  context = "act as a travel expert who plans travel itineraries worldwide"
  api_key = "b4697434f3a4b96oc63c0bff5tca4166"
  api_url = f"https://api.shecodes.io/ai/v1/generate?prompt={prompt}&context={context}&key={api_key}"

  response = requests.get(api_url)
  response_data = response.json()

  itinerary = Markdown(response_data["answer"])

  print(itinerary)

# welcome user function
def welcome_user():
  print(f"\n\n [bold blue] Welcome to this AI travel itinerary planner.[/bold blue]  \n\n")

# credits function
def closing_credits():
  print(f"\n\n [bold blue] This AI travel itinerary planner was coded in Python by Stella Bullo with SheCodes [/bold blue] \n\n")

# get user input: origin, destination, duration
origin = input("Enter the origin: ")
destination = input("Enter the destination: ")
duration = input("Enter the duration in days (enter only a number): ")

# display itinerary, weather in origin and destination
if origin and destination and duration.isdigit():
  welcome_user()
  generate_weather(origin)
  generate_weather(destination)
  generate_itinerary(origin, destination, duration)
  closing_credits()

else:
  print("Please enter all fields")

# final formatting, credits, etc.